### ISSUE TITLE
Questions about the paper and the code

### ISSUE THREAD

**Issue by JavaZeroo** [jeremyhengjm/DiffusionBridge#1]
Thank you very much for your great work! I'm just starting to learn diffusion bridge. there are a few things I don't understand that I hope you can answer:

1. why is the `learn_score_marginal` function used only in the `repeat_ou.ipynb` file? Based on my understanding of your paper, I think a complete training process should first use `learn_score_transition` and then `learn_score_marginal`, so that the diffusion bridge can be predicted completely.
2. what does the `learn_full_score_transition` function mean? I didn't see anything about it in the paper

---

Thank you very much for your valuable time! Looking forward to your reply!

**Comment by jeremyhengjm** [comment]
Hi there, 

1. the function `learn_score_marginal` is only required when one wants a forward time approximation of the diffusion bridge. This was used only in the Ornstein-Uhlenbeck experiments as we found that (for our purposes) it is typically sufficient and better to approximate the backward time representation of the diffusion bridge. That said the forward time representation could be useful for other problems. 
2. Yes please ignore the function `learn_full_score_transition` as it was used to experiment with an idea that we do not intend to have in the paper. 

I hope you find these responses helpful. Thanks for your interest in our work.

**Comment by JavaZeroo** [comment]
> Hi there,
> 
> 1. the function `learn_score_marginal` is only required when one wants a forward time approximation of the diffusion bridge. This was used only in the Ornstein-Uhlenbeck experiments as we found that (for our purposes) it is typically sufficient and better to approximate the backward time representation of the diffusion bridge. That said the forward time representation could be useful for other problems.
> 2. Yes please ignore the function `learn_full_score_transition` as it was used to experiment with an idea that we do not intend to have in the paper.
> 
> I hope you find these responses helpful. Thanks for your interest in our work.

Thank you for your reply, it helps me a lot!
